### PR TITLE
Mention platform-independent scripts

### PR DESCRIPTION
**Pull request by tomekwi**
# ”

Many npm scripts depend on Unix-only or bash-only features. If you want to make sure your scripts are platform-independent, keep to two rules:

* Only use cross-shell operators: `>`, `>>`, `<` and `|` – they work in bash, fish, the windows command prompt and others.
* Instead of platform-specific tools use node modules with a CLI – for example [`mkdirp`](https://www.npmjs.com/package/mkdirp) instead of `mkdir`, [`cpy`](https://www.npmjs.com/package/cpy) instead of `cp`, [`mve`](https://www.npmjs.com/package/mve) instead of `mv`.

### CODE REVIEW

**Comment by tomekwi** [comment]
By the way, I don’t know of any sensible shell-independent alternative to `;`, `&&` and `||`. Here’s my idea: <https://github.com/tomekwi/ideas/issues/1>.

What do you think @mattdesl @npm-scripts/owners?

**Comment by hemanth** [comment]
>'npm test' --and 'echo ✓' --or 'echo Test failed!!!' --then 'npm run build'

Sounds very right to me  :+1:

**Comment by mattdesl** [comment]
Nice, thanks for the PR! :+1: 

It would be great to have a separate repo that collects some information on compatibility. e.g. It might list operators/commands that work on unix + windows, and then list some modules that can be used as alternatives (like `cp`), and tools that can be used like your `--or` idea, and [parallelshell](https://www.npmjs.com/package/parallelshell).

**Comment by tomekwi** [comment]
> By the way, I don’t know of any sensible shell-independent alternative to ;, && and ||. Here’s my idea: tomekwi/ideas#1.

It seems that it’s OK to use `&&` and `||` after all. I sometimes just take info I find on stackoverflow for granted. But it turns out that this time an answer was wrong: <https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/ntcmds_shelloverview.mspx?mfr=true>.

**Pull request merged**
