### PR TITLE
Mention utility toolbelts

### PR DESCRIPTION
**Pull request by tomek-he-him**
Another exception to “always a single entry point”

### CODE REVIEW

**Comment by mattdesl** [comment]
I don't really agree with this. Single functions modules are not that hard to maintain.

Single functions provide clearer intent in your require statements and dependency trees. The package name `101`, `lodash`, `mout`, or `1-liners` doesn't tell me anything about what your code is doing, whereas [debounce](https://www.npmjs.com/package/debounce), [once](https://www.npmjs.com/package/once), [is-function](https://www.npmjs.com/package/is-function), are much more obvious. I can immediately tell which functions your module depends on even before I look at the code; this tends to give me greater confidence when choosing to rely on a module.

Semantic versioning becomes a problem with broadly scoped toolbags; you are more likely to run into major version changes when your module exports 100 functions. This makes de-duping more tedious.

Most of these libraries export a single entry-point for convenience, but in practice you end up with people writing modules that rely on this entry-point rather than the specific function they need. Almost every project I have worked on has run into multiple lodash/underscore/etc copies bundled because of some module deep in my dependency tree that brings in a 100kb utility belt for a single line function. Even Reddit was hit by this; it is tedious to go through making forks to fix this problem deep in your dependency tree.

There are so many dozens of "utility belts" now that all do the same thing with slightly different API semantics. There is no clear scope to these libraries, so they just continue to grow indefinitely, or until they have lost their fan following. They are never finished; unlike most small modules which are actually *frozen* and will never go "out of style."

This is why I would rather promote and encourage small and independently tested modules that follow best practices. If you can't find a one-liner on npm already, it isn't that hard to publish a new one that isn't tied to any particular toolbag. For most of these functions the maintenance cost is very low, since they will never need to be changed.

*It should be noted:* I have full respect for all the people working on lodash/underscore/ramda/etc. They have serious dedication to their libraries and have helped bring JavaScript as a language to new heights. Especially lodash, where a *lot* of the recent work has gone into splitting the code and publishing each function as its own module, which makes them much better for use in small modules.

**Comment by serapath** [comment]
I was wondering, what if...
```javascript
// ... i have a lot of modules like the one below following the unix philosophy...
module.exports = function singlePurposeFunction (/*...*/( {
  // ...
};
```
... and then, every developer by convention creates a repository `<conventionName>`,
maybe with the name:   "stack" or "framework" or something in this sense, which does nothing but:
```javascript
// http://github.com/username/<conventionName>/....
// => [./index.js] (=== require('package.json').main)
module.exports = {
  debounce: require('./debounce'),
  once: require('./once'),
  isFunction: require('./is-function')/*,
  ... */
};
// => [./debounce.js]
module.exports = require('debounce');
// => [./once.js]
module.exports = require('once');
// => [./is-function.js]
module.exports = require('is-function');
```
* This way, i can discuss and add all my favorite modules to one "package module" which is mine to maintain and evolve.
* It's represents my current state of opinion about what I use to build software. Instead of 'npm installing' a lot modules in each new project, I `require` my "stack" or "framework" and it brings in all my personal favorites.
* I can update/version my personal "stack" and others can be inspired
* **I can browser other peoples "favorite collection" and copy from them too.**
* All those versions of my personal "stack" can be made sure to "work together" (no version conflicts in case anyone released a new "version" and I can monitor my stack to be "up-to-date" and people can even message me about it.

### Example Usage:
```javascript
var stack = require('conventionName'); // npm install username/conventionName
// use
stack.once;
stack.debounce;
stack.isFunction;
// maybe "$" can even start to become the symbol for $tack and lose its old meaning and I would write:
$.once;
$.debounce;
$.isFunction;
```
Of course, not in every project I need all the `utilities`, `helpers` and whatnot of my personal stack, so i could easily do:
```javascript
var once = require('conventionName/once');
var debounce = require('conventionName/debounce');
var isFunction = require('conventionName/is-function');
// ... and save some bytes
```

**Comment by tomekwi** [comment]
@mattdesl I may not be objective here, because I take part in the development of 1-liners.

But as a user I like three things about these toolbelts:

* the API of each function is predictable (low cost of reading/writing documentation)
* composability – functions within one toolbelt cooperate well with one another
* low cost of discovering new modules – I sometimes end up wasting more time to find stuff deeply buried in https://npmjs.com or http://npmsearch.com than it would take to develop and test the logic myself

As an author I know how much time it takes to release a module – even if it’s one of these “small modules which are actually frozen and will never go out of style.” Specifying, documenting and adding a new function to a toolbelt is a breeze – everything is set up.

Versioning and bundling is not really a problem when you only allow `import plus from '1-liners/plus'` and not `import {plus} from '1-liners'`. It’s no problem when one package depends on `1-liners/plus` from 1-liners v1.0 and another on `1-liners/minus` from 1-liners v18.0.

> I can immediately tell which functions your module depends on even before I look at the code

This is definitely true – though I don’t see the gain in confidence. Supposing `lodash` was distributed this way and didn’t allow importing `lodash` – but only `lodash/drop`, `lodash/assign`, `lodash/zip`  and so on. I’d be confident choosing a module depending on it – whether it were for server-side or client-side code. I’d be more wary choosing something which has `another-drop`, `assign-like-a-boss`, `zip-plus` and ten others as dependencies. My mind only has a limited capacity of remembering high-quality modules.

**Comment by tomekwi** [comment]
@mattdesl, if you consider pulling this in, I agree that the PR would need to be reworded.

We’d have to mention the caveats you’re talking about and advise against a single entry point for such libraries.

**Comment by mattdesl** [comment]
(wall of text ahead...)

Regarding some of your points:

- API consistency is definitely valid. Though, to be honest, I generally spend more time reading through the docs *and sources* for lodash/mout/101/amp/ramda/etc and all their permutations since there are so many variations nowadays
- Composability, I'm not so sure about. Often, `ramda` functions are intended to be used alongside other `ramda` functions. It would be weird to see a module that brings in several fad toolkits (e.g. [mout](https://github.com/mout/mout), [amp](http://amp.ampersandjs.com/), [trine](https://github.com/jussi-kalliokoski/trine)) just for some `map` and `forEach` shims.
- Discovery is definitely an issue and kitchen sinks can help with this. But it doesn't mean all functions need to be in the same module; see lodash, [amp](http://amp.ampersandjs.com/) and [change-case](https://www.npmjs.com/package/change-case).

Maintainence is a valid point and we do need more tooling/education to help optimize the creation of many modules.

Constantly changing major SemVer means longer npm downloads (no caching) and deeper file nesting, but that's not a huge deal. More problematic is that version numbers have less meaning to users. It's clear that `once@2.0` has different semantics than `once@3.0`. It is not clear whether `fancy@2.0/once` is still compatible with `fance@3.0/once`.

> I’d be more wary choosing something which has drip-drop, assign-like-a-boss, zip-plus and ten others as dependencies

You might think the tiny module and open governance model will result in dozens of permutations of the same function with minute differences in the name. The reality is, there is not much duplication, and usually it's fairly obvious which modules are not safe to depend on.

On the other hand, you *do* end up with a *lot* of duplication and obscure module names when you add up all the kitchen sinks: lodash, mout, underscore, amp, 101, trine, functional.js, wu, fast.js, lazy.js, etc.

Because of this duplication, we now have `beep/fn/once` and `boop/functions/once` and `foo/once` ad infinitum, until we run out of trendy names and ways of re-inventing the Not-Invented-Here Toolbag Wheel. Meanwhile, they all do the same thing as `once`, which has been around a lot longer than the latest trend and will continue to be there after it's long forgotten.

Anyways, I'm not opposed to merging this. :smile: There are lots of good points on both sides. I think maybe using `lodash` or `change-case` would be a good example, since they both promote independently versioned modules.

**Comment by tomekwi** [comment]
> It's clear that once@2.0 has different semantics than once@3.0. It is not clear whether fancy@2.0/once is still compatible with fancy@3.0/once. 

Until now I’ve seen custom, per-function builds overkill – `'lodash.drop'`, `'lodash.once'`, etc. The `require('toolbag/function')` approach I first saw in 101 looked superiorly simple to me – lightweight, built into the language. But what you say is a good point.

> you do end up with a lot of NIH duplication and obscure module names when you add up all the kitchen sinks: lodash, mout, underscore, amp, 101, trine, functional.js, wu, fast.js, lazy.js, etc.
:+1: 

Duplication and scope creep are indeed real problems with toolbelts. We don’t want to end up with another ecosystem of monolithic Java-style all-inclusive libraries.

> Anyways, I'm not opposed to merging this. There are lots of good points on both sides.

Nice to hear that :) But to be honest, after our discussion I no longer see a perfect solution to these problems yet. At least not a generic one – as generic as your guide.

Perhaps something similar to what @serapath suggests isn’t a bad idea after all. Not on developer basis (I’ll still prefer to install `once@2.0` than `serapath-stack@21.0/once`) but on toolbelt basis. For example trine might just be a collection of external modules which follow the “data as `this`” convention. Ramda would be a set of modules “auto-curried, data as the last parameter”.

**Comment by serapath** [comment]
hey thx @tomekwi ,
i kind of was following and thought you are exactly discussing what i was trying to say :-)  

I feel there should be many *"single-purpose micro-modules"*, like e.g. `once` or `assign` or `drop`, of which very few and extremely well maintained versions exist and the community can brainstorm about best practice **interfaces** so that they easily compose - **BUT** the *"wrapping"* in a way that they compose could also be built into the ***"glue code"*** that each developer uses in his personal `stack/toolbelt/utilities`...

Then there will:
* `@tomekwi/stack@21.0/once`
* `@serapath/stack@18.0/once`
* `@mattdesl/stack@25.0/once`

I will always use my own `stack` and so should you or at least fork my stack if you don't have one yet.
Maybe it could also be called `utilities` or `toolbelt`, but a **community convention** would be GREAT, because it makes it super easy to browse the github profiles of productive developers and check how they choose to create their stack, so that i can adapt or discuss it if i feel like :-)

**Comment by ahdinosaur** [comment]
:-1: for kitchen sink toolbelts.

while i can understand having one repo to develop a collection of utility modules (as in `lodash`), i reckon the `require('toolbag/function)` goes against module best practices for all the reasons outlined above and [here](https://blog.andyet.com/2015/01/07/modularizing-underscorejs) and instead recommend if you have a collection of utility modules in one repo to follow the lodash@3 approach of publishing separate modules on npm as in `require('toolbag.function`)`, so consumers of the utility modules can treat it as a normal dependency.

**Comment by serapath** [comment]
@ahdinosaur :+1: 
The best of both worlds can be easily combined. :smile: 
* There should be a lot of **single purpose utility** functions/modules each developed in their own repository.
* There should be one repository per developer, where utility functions/modules are personally **curated**.
* There should be one main **usage** on one's own stack when developing repositories

## Usage
  * `npm install @ahdinosaur/stack`
  * `var once = require('stack/once);` or `var stack = require('stack);`

## Personal Curation
* **http://github.com/ahdinosaur/stack/**
  * **package.json**

    ```javascript
    { /* ... */ "main": "index.js" /* ... */ }
    ```
  * **index.js**

    ```javascript
    module.exports = {
      debounce       : require('./debounce'),
      once           : require('./once'),
      isFunction     : require('./is-function'),
      chunk          : require('./chunk')/*,
      ... */
    };
    ```
  * **chunk.js**

    ```javascript
    module.exports = require('lodash/array/chunk');
    ```
  * **debounce.js**

    ```javascript
    module.exports   = require('debounce');
    ```
  * **once.js**

    ```javascript
    module.exports   = require('once');
    ```
  * **is-function.js**

    ```javascript
    module.exports   = require('is-function');
    ```

This would make it easy to browse people's **stack**'s and discover useful utility functions and their combinations by exploring peoples other repositories and projects and see how they use and combine them. I even can start by forking someone's **stack** :smile: and everyone can version a personal stack and show to the world an opinionated best practice, which can then be discussed in issues and improved through pull requests.

**Comment by tomekwi** [comment]
@serapath I’m still not convinced the per-developer approach is a good thing. Looking at my projects I see that I use a different set of modules for every type of problem. It would be hard and tedious – if at all possible – to manually keep track of modules I use.

And besides, I see no advantage of `import('@tomekwi/stack/once');` over `import('once');`. And I do see a lot of work required to keep `@tomekwi/stack` up to date.

**Comment by serapath** [comment]
@tomekwi it shouldnt be a lot of work once you set it up. where do you see the problems?

1. on all your projects you do `npm install @tomekwi/stack --save` and you get a tested set of modules that you know, where otherwise you would install **many modules** where the current version of each might have introduced a breaking change. And you could use services to check you "stack" if something here is "out-of-date" and update it
2. you can even `npm install @someoneelse/stack @yetanotherperson/stack --save` and use those instead and combine them with yours and check those of skilled peers for inspiration.
3. people can easily check and discuss your stack to understand how you use/combine libraries and be inspired or give some tips for improvements. All beginners can follow those and learn about pros/cons of a certain approach and the philosophy behind that.

If you want, you could say, that https://github.com/jdalton is already doing it for https://github.com/lodash/lodash. It's in part his personal stack and lots of people use it and they are inspired. But there are a lot of awesome programers out there and it would benefit the whole ecosystem if they share their insights through a custom stack where it would even be possible to later run some analysis to see what trends emerge - it would otherwise not easily visible and that would be kind of sad.

**Comment by tomekwi** [comment]
> on all your projects you do npm install @tomekwi/stack --save

Ok, now I’m starting to get your point. You mean that most of my projects should have a single dependency on `@tomekwi/stack` – and whenever I have to add a dependency to my project, I rather add it to the stack first and then update the stack. Do I get it right?

> otherwise you would install many modules where the current version of each might have introduced a breaking change

And that is exactly the problem. Say you’ve built a cool project – say *boopifyer* – five months ago based on a cool library – like *async v1.2*. It depended on `@serapath/stack@25.0/async`. Since then a couple of libraries in your stack have had breaking changes and you had to bump your stack to v30. Now a version 1.4 of *async* is out – with great new features you need for your *boopifyer*. Normally you’d just update *async* and use the new features. Now you can’t because five other libraries from your stack have had breaking changes.

It reminds me a bit of the days I programmed in Python, where I had a system-wide set of libraries and all my projects depended on a subset of those. There were hacks to get around this – but all in all it was a design flaw of the language – common at that time.

> people can easily check your stack

If I want to check the stack of *substack* or *sindresorhus* I just look at the projects they’ve written and their dependencies.

> people can easily discuss your stack to understand how you use/combine libraries

Again, the best way to understand/discuss this is to look at a person’s project. A bare set of favorite modules tells little.

Besides, you can check the favourite modules of *substack* here: <https://github.com/stars/substack?language=javascript>.

> it would even be possible to later run some analysis to see what trends emerge

https://github.com/trending?l=javascript

**Comment by serapath** [comment]
ok, i get the point. makes sense.
So probably it would be really better to require all the libraries on their own, but on the other hand, this does not solve the following issue I experience:

The approach you are suggesting is the approach I'm currently taking, but it's not so easy for me, because people like *substack* or *sindresorhus* have >600 published packages and there are updates to many of them all the time, somtimes by contributors, sometimes by them, so in my experience its not trivial to figure out their current best practice compared to what they did think a year ago. It's a lot of work poking around, checking their projects, reading their source code and maybe I will get it, but to understand their current "best practice stack" is definitely a task of its own.

#### So:
In general - maybe I **should** take the time to update all my projects to my newest stack, but given lots of modules and limited time, maybe I would upgrade `async`, but not deal with other breaking changes that come with upgrading my `stack@25.0` to `stack@30.1`. So it would be great to have a way around that.

* Do you really think the use case you mention would be a common thing?
* And If so, it would concern old projects, because new projects you start with your most recent stack.
* It would also concern less successful projects, because successful ones get updates often enough

But when you need to update a project that was not touched for a long time, to get the new version of `async` while not wanting to update all the other changes that come with your new stack, you could just:
* `npm install async --save` and replace `require('@username/stack/async')` with `require('async')` to indicate this is an **out-of-ordinary-change**.
* the alternative would be - in case you want to really resurrect the project in a more general way - to actually take the time and update to you new stack.

What do you think? I feel indicating an "out-of-ordinary" legacy project update by directly installing `async` would work to get rid of all the down-sides you mentioned.

**Comment by tomekwi** [comment]
Regarding some of your points:

> The approach you are suggesting is the approach I'm currently taking, but it's not so easy for me

I understand. But I don’t think seasoned programmers would change their workflows when the change requires more labour and isn’t necessarily for the better.

There are many great resources for learning about best practices. Have you seen these?:
* https://github.com/sindresorhus/awesome
* http://substack.net/some_libraries_I_use_to_build_webapps

I guess that they tell you a lot more than just a set of modules without any indication how they’re mixed and matched.

> Do you really think the use case you mention would be a common thing?

I don’t think so. But it was just one concrete example of non-scalability. I could describe more, but I don’t have the time.

>  it would concern old projects, because new projects you start with your most recent stack.

Yeah – but if we measure age by outdated dependencies, such a project would grow old after a week or so.

> It would also concern less successful projects, because successful ones get updates often enough

I don’t agree. Read this: <http://substack.net/finding_modules#not-too-important>.

TBH @serapath I really think this would be a step backwards – towards hard, monolithic, stagnant dependency trees. Like in python, Java, C, ruby probably too.

**Comment by serapath** [comment]
What about an installer?
* `npm install @tomekwi/stack -g`
* `stack init`

This could execute
* `npm init` + (set some defaults regarding your default settings in `stack`
* `npm install --save ....`
* `npm install --save-dev ....`
where *....* stands for all your favorite modules, but I guess `yeoman` or `slush` or `forefront` or `cloverfield`.

**Comment by tomekwi** [comment]
@serapath I’m generally not a fan of using tools for things which are doable without them.

BTW I have a repo for boilerplate files: <https://github.com/tomekwi/boilerplate>.

**Comment by tomek-he-him** [comment]
Closing to remove clutter 🙂

Feel free to open if you think this is mergeable.

**Pull request closed without merging**
